initial commit: hw1
Oleg-Nik/DQE pull request #1
Opened 2021-02-10 13:38 UTC by Oleg-Nik

2021-02-10 19:15 UTC, a-chernov requested changes

2021-02-10 19:15 UTC, a-chernov commented on hw01.py
> +for _ in range(list_length): list_of_random_numbers[_] = random.randint(1, probability_range)
https://www.python.org/dev/peps/pep-0008/#other-recommendations

2021-02-10 19:15 UTC, a-chernov commented on hw01.py
> +for _ in range(list_length): list_of_random_numbers[_] = random.randint(1, probability_range)
Ты делаешь лишнее действие, зачем занимать память лишним объектом - списком из 6ой строки.
Создай пустой список и в цикле добавляй в него новые случайные значения.

2021-02-10 19:15 UTC, a-chernov commented on hw01.py
> +    sorted_list[i] = min_number
То же самое здесь

2021-02-10 19:15 UTC, a-chernov commented on hw01.py
> +even_sum = 0; odd_sum = 0
Снова https://www.python.org/dev/peps/pep-0008/#other-recommendations

2021-02-10 19:15 UTC, a-chernov commented on hw01.py
> +print("The sum of odd numbers:", odd_sum)
Думаю, в задании просили среднее, а не сумму

2021-02-16 14:44 UTC, Oleg-Nik commented on hw01.py
> +for _ in range(list_length): list_of_random_numbers[_] = random.randint(1, probability_range)
done

2021-02-16 14:45 UTC, Oleg-Nik commented on hw01.py
> +for _ in range(list_length): list_of_random_numbers[_] = random.randint(1, probability_range)
cycles chahged

2021-02-16 14:45 UTC, Oleg-Nik commented on hw01.py
> +    sorted_list[i] = min_number
done

2021-02-16 14:45 UTC, Oleg-Nik commented on hw01.py
> +even_sum = 0; odd_sum = 0
changed

2021-02-16 14:46 UTC, Oleg-Nik commented
corrected

2021-02-16 14:48 UTC, a-chernov approved these changes

2021-02-16 14:49 UTC, merged